name: Code Change Analysis

on:
  push:
    branches: [ main, master, dev ]  # Customize branches as needed

jobs:
  analyze-code-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch complete history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install GitPython tree_sitter
        # Install language parsers for tree-sitter
        pip install tree-sitter-python tree-sitter-javascript tree-sitter-typescript tree-sitter-java tree-sitter-go tree-sitter-rust

    - name: Analyze code changes
      run: |
        mkdir -p .docai
        python .github/scripts/analyze_code_changes.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug .docai contents
      run: |
        ls -la .docai/ || echo ".docai/ is empty or missing"
        cat .docai/* || echo "No files to display"

    - name: Commit and push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .docai
          # Only commit if there are changes
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update analysis results"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
          
    - name: Store analysis results
      uses: actions/upload-artifact@v4
      with:
        name: code-analysis
        path: .docai/
